### ISSUE TITLE
3.X 代码

### ISSUE THREAD

**Issue by MeowStone** [Shu-Ji/wechat_micro_jump_game_hero#3]
```python
# coding: u8

from __future__ import print_function, unicode_literals

import colorsys
import os
import itertools
import math
import time
import traceback

from PIL import Image, ImageDraw


class Otsu(object):

    def __init__(self, path, debug=True):
        print(path)
        self.im = Image.open(path)

        self.w, self.h = self.im.size
        self.pixels = self.im.load()
        self.draw = ImageDraw.Draw(self.im)

        self.hero_pos = self.find_hero()
        print('hero pos:', self.hero_pos)

        is_hero_on_left = self.hero_pos[0] < self. w / 2

        bg_hsv = self.get_background_hsv()
        print('background hsv:', bg_hsv)

        top_most, lr_most = self.find_most(is_hero_on_left, bg_hsv)
        print('top most pos：', top_most)
        print('left/right most pos', lr_most)

        self.center_pos = top_most[0], lr_most[1]
        print('center pos', self.center_pos)

        if debug:
            #self.erase_background(bg_hsv)
            self.draw_pos(self.hero_pos)
            self.draw_pos(top_most)
            self.draw_pos(lr_most)
            self.draw_pos(self.center_pos)

            cx, cy = self.center_pos
            hx, hy = self.hero_pos
            self.draw.line((cx, cy, hx, hy), fill=(0, 255, 0), width=8)

            self.im.show()

    def find_hero(self):
        hero_poses = []
        for y in range(self.h / 3, self.h * 2 / 3):
            for x in range(self.w):
                # is purple
                if self.pixels[x, y] == (56, 56, 97, 255):
                    hero_poses.append((x, y))
        # calc the avg pos
        return map(lambda i: sum(i) / len(i), itertools.izip(*hero_poses))

    def rgb_to_hsv(self, r, g, b, a=255):
        h, s, v = colorsys.rgb_to_hsv(r / 255., g / 255., b / 255.)
        return int(h * 255.), int(s * 255.), int(v * 255.)

    def get_background_hsv(self):
        # use the (10, 800) as the background color
        bg_color = self.pixels[10, 800]
        return self.rgb_to_hsv(*bg_color)

    def erase_background(self, bg_hsv):
        for y in range(self.h / 4, self.h * 2 / 3):
            for x in range(self.w):
                h, s, v = self.rgb_to_hsv(*self.pixels[x, y])
                if self.is_same_color(h, s, v, bg_hsv):
                    self.im.putpixel((x, y), (0, 0, 0))
                else:
                    self.im.putpixel((x, y), (255, 255, 255))

    def find_most(self, is_hero_on_left, bg_hsv):
        hero_r = 15
        if is_hero_on_left:
            # top most is on the right, scan from right
            from_x = self.w - 1
            to_x = self.hero_pos[0] + hero_r
            step = -1
        else:
            # top most is on the left, scan from left
            from_x = 0
            to_x = self.hero_pos[0] - hero_r
            step = 1

        from_y, to_y = self.h / 4, self.hero_pos[1]

        top_most = self.find_top_most(bg_hsv, from_x, to_x, from_y, to_y, step)
        lr_most = self.find_lr_most(bg_hsv, from_x, to_x, from_y, to_y, step)
        return top_most, lr_most

    def find_top_most(self, bg_hsv, from_x, to_x, from_y, to_y, step):
        for y in range(from_y, to_y):
            for x in range(from_x, to_x, step):
                h, s, v = self.rgb_to_hsv(*self.pixels[x, y])
                if not self.is_same_color(h, s, v, bg_hsv):
                    return x, y

    def find_lr_most(self, bg_hsv, from_x, to_x, from_y, to_y, step):
        for x in range(from_x, to_x, step):
            for y in range(from_y, to_y):
                h, s, v = self.rgb_to_hsv(*self.pixels[x, y])
                if not self.is_same_color(h, s, v, bg_hsv):
                    return x, y

    def is_same_color(self, h, s, v, bg_hsv):
        bg_h, bg_s, bg_v = bg_hsv
        return (abs(h - bg_h) < 15) and (abs(s - bg_s) < 20)

    def draw_pos(self, pos, color=(0, 255, 0)):
        x, y = pos
        r = 25
        self.draw.ellipse((x, y, x + r, y + r), fill=color, outline=color)

    def get_holding(self):
        line_length = int(math.sqrt(
            pow(self.center_pos[0] - self.hero_pos[0], 2) + \
            pow(self.center_pos[1] - self.hero_pos[1], 2)
        ))

        length_time = line_length * 1.5

        holding = min(950, max(length_time, 300))

        print('length, duration, holding: ', line_length, length_time, holding)
        print()

        return int(holding)


def run_cmd(cmd):
    return os.system(cmd)
    # return commands.getstatusoutput(cmd)


jump_times = itertools.count(0)
while True:
    try:
        debug = True

        if debug:
            fn = 's'
        else:
            fn = str(next(jump_times))
            run_cmd('adb shell screencap -p /sdcard/s.png')
            run_cmd('adb pull /sdcard/s.png /tmp/{}.png'.format(fn))
            run_cmd('cp /tmp/{}.png /tmp/s.png'.format(fn))
            print(fn)

        holding = Otsu('/tmp/{}.png'.format(fn), debug=debug).get_holding()

        if debug:
            raise KeyboardInterrupt
        else:
            run_cmd('adb shell input swipe 255 255 0 0 {}'.format(holding))
            time.sleep(2)
    except KeyboardInterrupt:
        raise KeyboardInterrupt
    except Exception as e:
        traceback.print_exc()
        time.sleep(2)
```
代码修改了，更换了3.X环境下的依赖包
小米5s跑的，找不到文件错误

**Comment by Shu-Ji** [comment]
不好意思，高亮有点问题，我帮您修改了一下。

找不到文件错误是指？

通过执行 `pipenv install` 安装相关依赖了吗？

**Comment by MeowStone** [comment]
@Shu-Ji 依赖问题解决了，comands换成os，PIL换成pillow，但是图片保存的路径在每个手机是不一样的，这5s应该是/storage/emulated/0/

**Comment by Shu-Ji** [comment]
@MeowStone 明白了，不知道 Android 的 /tmp/ 目录是否可用。

commands 可以换成 subprocess.popen，os.system 貌似会输出多余信息。

**Comment by MeowStone** [comment]
Traceback (most recent call last):
  File "main.py", line 158, in <module>
    holding = Otsu('/tmp/{}.png'.format(fn), debug=debug).get_holding()
  File "main.py", line 19, in __init__
    self.im = Image.open(path)
  File "E:\Workspace\py\venv\lib\site-packages\PIL\Image.py", line 2543, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/s.png'

这是路径报错

**Comment by Shu-Ji** [comment]
```python

run_cmd('adb shell screencap -p /sdcard/s.png')  # 截手机的图到手机的/sdcard/s.png
run_cmd('adb pull /sdcard/s.png /tmp/{}.png'.format(fn))  # 将上面的截图/sdcard/s.png 拉取到电脑的/tmp/s.png
print(fn)

holding = Otsu('/tmp/{}.png'.format(fn), debug=debug).get_holding()  # 打开电脑的 /tmp/s.png
```

这是因为我的开发环境是 linux，你的是 windows 导致的。

Otsu传入的的本地电脑的路径，不是手机的路径，所以 windows 改成你相应截图存放路径。

**Comment by MeowStone** [comment]
@Shu-Ji 能具体说明改哪些？ /tmp/{}.png这个？

**Comment by Shu-Ji** [comment]
@MeowStone 

示例：

```python

run_cmd('adb shell screencap -p /sdcard/s.png')  # 截手机的图到手机的/sdcard/s.png
run_cmd('adb pull /sdcard/s.png E:/mytmpdir/{}.png'.format(fn))  # 将上面的截图/sdcard/s.png 拉取到电脑的E:/mytmpdir/s.png
print(fn)

holding = Otsu('E:/mytmpdir/{}.png'.format(fn), debug=debug).get_holding()  # 打开电脑的 E:/mytmpdir/s.png
```

示例中对于路径的处理，我不太清楚 windows 的 / 和 \，相应修改一个就行
