### ISSUE TITLE
 No such file or directory: u'/tmp/0.png'

### ISSUE THREAD

**Issue by hanmingkang** [Shu-Ji/wechat_micro_jump_game_hero#7]
Traceback (most recent call last):
  File "D:/PythonTest/python/main.py", line 156, in <module>
    holding = Otsu('/tmp/{}.png'.format(fn), debug=debug).get_holding()
  File "D:/PythonTest/python/main.py", line 18, in __init__
    self.im = Image.open(path)
  File "D:\PythonTest\venv\lib\site-packages\PIL\Image.py", line 2543, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: u'/tmp/0.png'

**Comment by Shu-Ji** [comment]
@ksx159 请参考：https://github.com/Shu-Ji/wechat_micro_jump_game_hero/issues/3 关于 Windows 下的使用说明
